export const membershipPlans = [
  {
    id: "1month",
    name: "1 Month",
    duration: "1 Month",
    price: "1,000",
    admissionFee: "+ ₹500 Admission Fee",
    benefits: [
      "Full gym floor access",
      "Personalized fitness assessment",
      "Access to group classes",
    ],
  },
  {
    id: "3month",
    name: "3 Months",
    duration: "3 Months",
    price: "3,000",
    admissionFee: null,
    badge: "ZERO ADMISSION FEE",
    benefits: [
      "Full gym floor access",
      "No admission fee charged",
      "1 free trainer consultation",
    ],
  },
  {
    id: "6month",
    name: "6 Months",
    duration: "6 Months",
    price: "5,300",
    originalPrice: "6,000",
    admissionFee: "+ Admission Fee Applicable",
    isPopular: true,
    benefits: [
      "Full gym floor access",
      "₹700 instant discount applied",
      "Dedicated trainer guidance",
      "Free diet consultation",
    ],
  },
  {
    id: "1year",
    name: "1 Year",
    duration: "12 Months",
    price: "10,500",
    originalPrice: "12,000",
    admissionFee: "+ Admission Fee Applicable",
    badge: "BEST VALUE",
    benefits: [
      "Full gym floor access",
      "₹1,500 instant discount applied",
      "Priority trainer support",
      "Free diet & nutrition plan",
      "Complimentary gym merchandise",
    ],
  },
  {
    id: "student",
    name: "Student Plan",
    duration: "Billed Monthly",
    price: "800",
    priceSuffix: "/mo",
    admissionFee: "+ Admission Fee Applicable",
    badge: "STUDENT SPECIAL",
    note: "Valid for students up to Class 12",
    benefits: [
      "Full gym floor access",
      "Valid up to Class 12",
      "Basic fitness guidance",
    ],
  },
];
