import { Check, ExternalLink, Mail, MapPin, Phone } from 'lucide-react';
import { useEffect } from 'react';
import BackToTop from '../components/legal/BackToTop';
import LegalHero from '../components/legal/LegalHero';
import LegalSection from '../components/legal/LegalSection';
import ScrollProgress from '../components/legal/ScrollProgress';
import TableOfContents from '../components/legal/TableOfContents';
import { address, email, gym_full_name, phone_number, website_link } from '../constants/constants';

const items = [['information', 'Information We Collect'], ['use', 'How We Use Information'], ['protection', 'Data Protection'], ['sharing', 'Information Sharing'], ['rights', 'Your Rights'], ['cookies', 'Cookies'], ['updates', 'Policy Updates'], ['contact', 'Contact']];
const BulletList = ({ children }) => <ul className="space-y-2.5">{children.map((item) => <li key={item} className="flex gap-3"><Check className="mt-1 h-4 w-4 shrink-0 text-rose-400" /><span>{item}</span></li>)}</ul>;
const Group = ({ title, children }) => <div><h3 className="mb-2 font-semibold text-slate-100">{title}</h3><BulletList>{children}</BulletList></div>;
const Contact = () => <div className="grid gap-3 rounded-xl border border-white/8 bg-black/20 p-5 text-sm sm:grid-cols-2"><p className="font-semibold text-slate-100 sm:col-span-2">{gym_full_name}</p><p className="flex gap-2"><MapPin className="h-4 w-4 shrink-0 text-rose-400" />{address}</p><p className="flex gap-2"><Mail className="h-4 w-4 shrink-0 text-rose-400" />{email}</p><p className="flex gap-2"><Phone className="h-4 w-4 shrink-0 text-rose-400" />{phone_number}</p><p className="flex gap-2"><ExternalLink className="h-4 w-4 shrink-0 text-rose-400" />{website_link}</p></div>;

const PrivacyPolicy = () => {
  useEffect(() => { document.title = 'Privacy Policy | DCore Fitness Zone'; document.querySelector('meta[name="description"]')?.setAttribute('content', 'Learn how DCore Fitness Zone collects, stores and protects your personal information.'); window.scrollTo(0, 0); }, []);
  return <><ScrollProgress /><LegalHero label="Legal" title="Privacy Policy" description="A clear explanation of how DCore Fitness Zone collects, uses, and protects your personal information." /><div className="mx-auto grid max-w-7xl gap-8 px-5 py-12 sm:px-8 lg:grid-cols-[250px_minmax(0,1fr)] lg:py-16"><TableOfContents items={items.map(([id, title]) => ({ id, title }))} /><article className="space-y-5"><LegalSection id="information" title="Information We Collect"><p>We collect only the information needed to operate and improve your membership experience.</p><Group title="Personal Information">{['Name', 'Email', 'Phone', 'Gender']}</Group><Group title="Membership Information">{['Membership plan', 'Status']}</Group><Group title="Attendance Information">{['Check-in history']}</Group><Group title="Health Information">{['Height', 'Weight', 'Fitness goals', 'Medical conditions (optional)']}</Group><Group title="Payment Information">{['Amount', 'Date', 'Payment method', 'Verification status']}</Group></LegalSection><LegalSection id="use" title="How We Use Information"><BulletList>{['Manage memberships', 'Verify payments', 'Track attendance', 'Maintain member records', 'Improve services', 'Respond to support requests']}</BulletList></LegalSection><LegalSection id="protection" title="Data Protection"><p>Personal information is stored securely. We use reasonable technical and organisational measures designed to protect your data, though no online system can guarantee absolute security.</p></LegalSection><LegalSection id="sharing" title="Information Sharing"><p>Personal information is never sold. It is only shared where necessary with:</p><BulletList>{['Authorised staff', 'Trusted service providers', 'Authorities when required by law']}</BulletList></LegalSection><LegalSection id="rights" title="Your Rights"><p>Members may request:</p><BulletList>{['Access to their personal information', 'Correction of inaccurate information', 'Account deletion where legally permitted']}</BulletList></LegalSection><LegalSection id="cookies" title="Cookies"><p>Cookies are used only for login sessions, security, and improving the user experience. Disabling cookies may affect some application functionality.</p></LegalSection><LegalSection id="updates" title="Policy Updates"><p>This Privacy Policy may be updated as our services or legal obligations change. The latest version will always be available on this page.</p></LegalSection><LegalSection id="contact" title="Contact"><p>For privacy questions or requests, please contact us:</p><Contact /></LegalSection></article></div><BackToTop /></>;
};
export default PrivacyPolicy;
