import { Check, ExternalLink, Mail, MapPin, Phone } from 'lucide-react';
import { useEffect } from 'react';
import BackToTop from '../components/legal/BackToTop';
import LegalHero from '../components/legal/LegalHero';
import LegalSection from '../components/legal/LegalSection';
import ScrollProgress from '../components/legal/ScrollProgress';
import TableOfContents from '../components/legal/TableOfContents';
import { address, email, gym_full_name, phone_number, website_link } from '../constants/constants';

const items = [
  ['acceptance', 'Acceptance'], ['membership', 'Membership'], ['responsibilities', 'User Responsibilities'], ['health', 'Health Responsibility'], ['property', 'Intellectual Property'], ['liability', 'Limitation of Liability'], ['changes', 'Changes'], ['contact', 'Contact'],
];
const BulletList = ({ children }) => <ul className="space-y-2.5">{children.map((item) => <li key={item} className="flex gap-3"><Check className="mt-1 h-4 w-4 shrink-0 text-rose-400" /><span>{item}</span></li>)}</ul>;
const Contact = () => <div className="grid gap-3 rounded-xl border border-white/8 bg-black/20 p-5 text-sm sm:grid-cols-2"><p className="font-semibold text-slate-100 sm:col-span-2">{gym_full_name}</p><p className="flex gap-2"><MapPin className="h-4 w-4 shrink-0 text-rose-400" />{address}</p><p className="flex gap-2"><Mail className="h-4 w-4 shrink-0 text-rose-400" />{email}</p><p className="flex gap-2"><Phone className="h-4 w-4 shrink-0 text-rose-400" />{phone_number}</p><p className="flex gap-2"><ExternalLink className="h-4 w-4 shrink-0 text-rose-400" />{website_link}</p></div>;

const TermsAndConditions = () => {
  useEffect(() => { document.title = 'Terms & Conditions | DCore Fitness Zone'; document.querySelector('meta[name="description"]')?.setAttribute('content', 'Read the Terms & Conditions for using the DCore Fitness Zone Gym Management System.'); window.scrollTo(0, 0); }, []);
  return <><ScrollProgress /><LegalHero label="Legal" title="Terms & Conditions" description="The terms that help keep the DCore Fitness Zone experience clear, fair, and secure for every member." /><div className="mx-auto grid max-w-7xl gap-8 px-5 py-12 sm:px-8 lg:grid-cols-[250px_minmax(0,1fr)] lg:py-16"><TableOfContents items={items.map(([id, title]) => ({ id, title }))} /><article className="space-y-5"><LegalSection id="acceptance" title="Acceptance"><p>Using this application means you agree to these Terms and Conditions. If you do not agree, please do not create an account or use the DCore Fitness Zone Gym Management System.</p></LegalSection><LegalSection id="membership" title="Membership"><p>Membership becomes active only after payment verification by the gym administrator. Membership plans, pricing, durations, and benefits may change without prior notice.</p></LegalSection><LegalSection id="responsibilities" title="User Responsibilities"><p>To maintain a reliable community, users must:</p><BulletList>{['Provide accurate and current information', 'Keep passwords secure and report unauthorised access', 'Follow gym rules and respect staff', 'Not misuse, disrupt, or attempt to compromise the application']}</BulletList></LegalSection><LegalSection id="health" title="Health Responsibility"><p>Members are responsible for ensuring they are medically fit before participating in workouts. Any health information provided to us should be accurate and kept up to date.</p></LegalSection><LegalSection id="property" title="Intellectual Property"><p>All logos, branding, software, designs, source code, and content belong to DCore Fitness Zone. They may not be reproduced or used without our written permission.</p></LegalSection><LegalSection id="liability" title="Limitation of Liability"><p>To the extent permitted by law, the gym is not responsible for:</p><BulletList>{['Service interruptions or planned maintenance', 'Technical failures outside our reasonable control', 'Losses caused by incorrect information supplied by members']}</BulletList></LegalSection><LegalSection id="changes" title="Changes"><p>These Terms may change at any time to reflect our services or legal requirements. Continued use of the application after an update means you accept the revised Terms.</p></LegalSection><LegalSection id="contact" title="Contact"><p>For questions about these Terms, please contact us:</p><Contact /></LegalSection></article></div><BackToTop /></>;
};
export default TermsAndConditions;
